CREATE DATABASE mycontacts;

/* CREATE A EXTESION FOR USE UUID IN PSQL */
/* IF NOT EXISTS -> RESERVATION KEYWORD */

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

/* DEFAULT -> RESERVATION KEYWORK AND GET A DEFAULT VALUE, IN THIS CASE,
   THE EXTESION OF UUID (uuid_generate_v4())
*/

CREATE TABLE IF NOT EXISTS categories (
  id UUID NOT NULL UNIQUE DEFAULT uuid_generate_v4(),
  name VARCHAR NOT NULL
);
/*
\dt -> list tables
*/
CREATE TABLE IF NOT EXISTS contacts (
  id UUID NOT NULL UNIQUE DEFAULT uuid_generate_v4(),
  name VARCHAR NOT NULL,
  email VARCHAR UNIQUE,
  phone VARCHAR,
  categorie_id UUID,
  FOREIGN KEY(categorie_id) REFERENCES categories(id)
);
